server:
  tomcat:
    max-threads: 4
  compression:
    enabled: true
    mime-types: 'application/json'
    min-response-size: 1024

spring:
  jackson:
    default-property-inclusion: 'NON_NULL'
  datasource:
    url: jdbc:h2:file:./data/local-prod;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect